### ISSUE TITLE
Release 1.4.0 is broken with Docker: missing parentheses in call to `print`

### ISSUE THREAD

**Issue by israel-tk** [onelogin/onelogin-python-aws-assume-role#14]
A recent commit introduced some lines with `print "something"` like https://github.com/onelogin/onelogin-python-aws-assume-role/blob/master/src/onelogin/aws-assume-role/aws-assume-role.py#L215 which are not allowed in Python 3. Simply change it to `print("something")`.

**Comment by israel-tk** [comment]
BTW I suggest some CI to check that the code is compatible with Python 2 and 3 on every build. :)

**Comment by pitbulk** [comment]
Thanks for the PR, you are right.

**Comment by israel-tk** [comment]
Can we push a release 1.4.1?

**Comment by pitbulk** [comment]
Done

**Comment by pitbulk** [comment]
@israel-tk you are right now the most active dev using the script, do you have any feedback to share?

**Comment by israel-tk** [comment]
@pitbulk not right now, but will contact you whenever I have some! :)
