### ISSUE TITLE
Please release 1.5 to PyPi

### ISSUE THREAD

**Issue by tjbaker** [onelogin/onelogin-python-aws-assume-role#23]
Please release version 1.5 to PyPi.  The latest on PyPi is 1.4.5

Thanks!

**Comment by pitbulk** [comment]
1.5 isn't ready

As you can see on #20 and #22 there was some work to improve the way the project was packaged, but I found some issue, so I'm still waiting a reply from @kylecrawshaw to clarify.

**Comment by tjbaker** [comment]
I suggest not-ready releases should be tagged differently from ready ones.  Typically one would use a different pattern, or not tag as a release at all to avoid confusion such as this.

**Comment by pitbulk** [comment]
I accidentally published the tag 1.5.0 here.

**Comment by kylecrawshaw** [comment]
Now that #22 has been merged I assume there should be a release of 1.5 coming soon?

**Comment by tjbaker** [comment]
I think you can close this.
