### ISSUE TITLE
Please release 1.5.1 to PyPi

### ISSUE THREAD

**Issue by 166MMX** [onelogin/onelogin-python-aws-assume-role#29]
https://pypi.org/project/onelogin-aws-assume-role/ 
Is missing the lates 1.5.1 bug fix release.

**Comment by pitbulk** [comment]
The Writer fix has issues.

https://github.com/onelogin/onelogin-python-aws-assume-role/pull/27#issuecomment-471132838

That why I have not officially released 1.5.1

**Comment by bzvestey** [comment]
Version 1.10.0 has been released.
