### ISSUE TITLE
400 error debugging

### ISSUE THREAD

**Issue by s-vakati** [onelogin/onelogin-python-aws-assume-role#34]
I am pretty sure I might be doing something wrong.
One login support mentioned I should create an issue here for this client.
I am getting a 400 error when I run the client:

OneLogin Username: 
my-company-username

OneLogin Password:
my-company-id-login-password

AWS App ID:
AWS-App-id-for-my-company

Onelogin Instance Sub Domain:
company-name.onelogin.com

I get a 400 error. What could be wrong with my input?

**Comment by pitbulk** [comment]
In addition to the code error, you should be able to see a message that specified the cause for the error.
