### ISSUE TITLE
OTP Token for Yubico YubiKey Fails

### ISSUE THREAD

**Issue by itomaldonado** [onelogin/onelogin-python-aws-assume-role#37]
Trying to use Yubico YubiKey as my OTP does not work with this script (but *does* work with the Onelogin webpage). This is what I get:

```
OneLogin AWS Assume Role Tool


MFA Required
Authenticate using one of these devices:
-----------------------------------------------------------------------
 0 | Yubico YubiKey
 1 | Some Other Authenticator
-----------------------------------------------------------------------

Select the desired MFA Device [0-1]: 
0
Enter the OTP Token for Yubico YubiKey: 
<some-hash...>
The OTP Token was not able to be processed, please introduce a new one:
<another-hash>
The OTP Token was not able to be processed, please introduce a new one:
```

**Comment by pitbulk** [comment]
There was a recent change (yesterday) on YubicoCloud that broke the integration.
We fixed the Login flow but this script uses the API with is not yet fixed.

Check the Onelogin Status page:
https://www.onelogin.com/status

**Comment by itomaldonado** [comment]
Thanks for the information!

@pitbulk started working again as of Feb 4 2020, 2:00 PM East~

I can close this now~
