### ISSUE TITLE
Duo integration problem

### ISSUE THREAD

**Issue by radsec** [onelogin/onelogin-python-aws-assume-role#44]
I am having an issue even trying to prompt push or using the duo codes. I can confirm the code is correct. If there is an alternative to creating an app policy that can require a different OTP factor and restrict it to that, that would be an adequate work-around.

![image](https://user-images.githubusercontent.com/39590744/79391731-f094f480-7f26-11ea-9389-8f37362277a6.png)

**Comment by pitbulk** [comment]
Duo is not supported by our [Verify Factor API](https://developers.onelogin.com/api-docs/1/multi-factor-authentication/verify-factor)
