### ISSUE TITLE
--profile flag doesn't include a new line before [] breaking existing creds files

### ISSUE THREAD

**Issue by bobbytables** [onelogin/onelogin-python-aws-assume-role#7]
The profile name that gets slapped into the `~/.aws/.credentials` file doesn't include a new line before it so it breaks the entire credentials file:

Given the flag `portal`:

```
[production]
aws_access_key_id={obfuscated}
aws_secret_access_key={obfuscasted}[portal]
aws_secret_access_key = all of this is wrong now
```

**Comment by pitbulk** [comment]
I will review it asap

**Comment by pitbulk** [comment]
I copied the code to handle and store credentials from the official aws-cli:
https://github.com/aws/aws-cli/blob/master/awscli/customizations/configure/writer.py

And it seems it contains also the bug you reported.
